### ISSUE TITLE
从恩山来的,大佬考虑在源分类加下是电信还是联通吗

### ISSUE THREAD

**Issue by MemoryCollection** [ssili126/tv#10]

**Comment by ssili126** [comment]
以前有考虑增加电信联通移动等分类，也考虑增加不同省份等的分类，但测试并不理想，同省份的不一定是最合适的，最后所有频道经过实际下载测速，取最优的几个频道，播放是最好的，最流畅的。因为是每个频道下载测速，花的时间也比较长，好在是电脑自己操作。

**Comment by MemoryCollection** [comment]
> 以前有考虑增加电信联通移动等分类，也考虑增加不同省份等的分类，但测试并不理想，同省份的不一定是最合适的，最后所有频道经过实际下载测速，取最优的几个频道，播放是最好的，最流畅的。因为是每个频道下载测速，花的时间也比较长，好在是电脑自己操作。

好的,谢谢大佬

**Comment by MemoryCollection** [comment]
> 以前有考虑增加电信联通移动等分类，也考虑增加不同省份等的分类，但测试并不理想，同省份的不一定是最合适的，最后所有频道经过实际下载测速，取最优的几个频道，播放是最好的，最流畅的。因为是每个频道下载测速，花的时间也比较长，好在是电脑自己操作。

嗯嗯,谢谢大佬分享.请教下 我想在宝塔添加项目运行,大佬知道应该怎么设置吗?框架和运行方式怎么选择拿?
![image](https://github.com/ssili126/tv/assets/27777606/61425668-3705-439b-b49b-cef10188fdc0)
