### ISSUE TITLE
用itvtest.exe时报错

### ISSUE THREAD

**Issue by namenameq** [ssili126/tv#11]
用itvtest.exe时报错，提示
Traceback (most recent call last):
  file "download_speed.py", line 24, in<module>
ValueError: too many values to unpack (expected 2)
[38212] Failed to execute script 'download_speed' due to unhandled exception!
请问这个要怎么处理？谢谢

**Comment by ssili126** [comment]
这个是个别频道格式更新，因我现在没有电脑，没法生成新的程序，github生成的windows文件有问题，故windows文件没有更新。但是新的py文件是可以使用的，已经更新。

**Comment by ssili126** [comment]
现在可以暂时直接引用itvlist.txt使用。可以使用下面的地址：https://ghproxy.net/https://raw.githubusercontent.com/ssili126/tv/main/itvlist.txt

**Comment by namenameq** [comment]
好的，谢谢！你测速用的download_speed.py应该是直接打包在itvtest.exe里，所以只能等你更新windows文件夹里文件，不过我把py放到宝塔里面启动不了，py用的是哪个版本？

**Comment by ssili126** [comment]
py用的3.9，好像以后的版本都可以，以前的版本没有测试。

**Comment by ssili126** [comment]
用itv.py和itvtest.py两个就可以

**Comment by ssili126** [comment]
更新了itv.exe文件，
