### ISSUE TITLE
2月18号使用itvtest.exe提示报错

### ISSUE THREAD

**Issue by redscarful** [ssili126/tv#12]
C:Users 1\Downloads Programs itvtest.exe
raceback lmost recent call last]File“download speed.py”， line 24,in <module>falueError: too many values to upack (expected 2)
2336] Failed to execute script download speed
due to unhandled exception!
请问这是什么问题，第一次使用可以，第二次就不行了

**Comment by ssili126** [comment]
这个文件没有更新，放假中，没有电脑。python文件可以正常使用。

**Comment by redscarful** [comment]
原来是这样啊，哈哈我第一次测试了一下可以运行的，第二次就不行了奇怪，py文件我不知道如何运行，有没有空说下依赖两个py文件如何运行，我是小白不太懂，莫怪

ssili126 ***@***.***> 于2024年2月18日周日 17:36写道：

**Comment by redscarful** [comment]
😂

刘大嫂已通过 Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>
做出回应

刘大嫂 ***@***.***> 于2024年2月19日周一 08:26写道：

**Comment by ssili126** [comment]
更新了itv.exe文件。

**Comment by redscarful** [comment]
![Uploading 微信截图_20240221095706.png…]()

**Comment by redscarful** [comment]
![Uploading 微信截图_20240221095706.png…]()

**Comment by ssili126** [comment]
再试试，现在可以了，以前只是没有输出窗口，哈哈，

**Comment by redscarful** [comment]
好的，刚刚吓我一跳，加个v,一会就删掉

**Comment by redscarful** [comment]
可以运行了，不知道为什么生成不了txt

**Comment by ssili126** [comment]
我测试没有问题，有显示什么信息吗？

**Comment by redscarful** [comment]
能不能加个v啊，谢谢了

**Comment by redscarful** [comment]
刚刚进行了测试，可以使用了

**Comment by redscarful** [comment]
感觉测试的速度有点慢了，不如之前快了

**Comment by redscarful** [comment]
运行好几次itvtest.exe，运行正常，中途会卡住不动，是哪里的问题

**Comment by ssili126** [comment]
可以啊，我加你v，

**Comment by redscarful** [comment]
rencsarful

**Comment by ssili126** [comment]
中途卡住可能是电脑处理的问题，

**Comment by redscarful** [comment]
v：redscarful
