### ISSUE TITLE
itv py抓的txt UDP是否有异常呀

### ISSUE THREAD

**Issue by nomoneynolife** [ssili126/tv#13]
http://x.x.x.x:9901udp://@x.x.x.x:10001

这不像是规范的格式，请大佬看看

**Comment by ssili126** [comment]
这些已经舍弃了，频道太多了。保留是想给想折腾的人留着。这个是抓取时的ip：http://x.x.x.x:9901，这个是抓取时的频道播放地址：udp//@x.x.x.x:10001

**Comment by nomoneynolife** [comment]
> 这些已经舍弃了，频道太多了。保留是想给想折腾的人留着。这个是抓取时的ip：[http://x.x.x.x:9901，这个是抓取时的频道播放地址：udp//@x.x.x.x:10001](http://x.x.x.x:9901%EF%BC%8C%E8%BF%99%E4%B8%AA%E6%98%AF%E6%8A%93%E5%8F%96%E6%97%B6%E7%9A%84%E9%A2%91%E9%81%93%E6%92%AD%E6%94%BE%E5%9C%B0%E5%9D%80%EF%BC%9Audp//@x.x.x.x:10001)
原来如此~
