### ISSUE TITLE
无法播放

### ISSUE THREAD

**Issue by cn0068** [ssili126/tv#2]
建议读取到有效数据后, 测试一下播放. 目前收集到的很多都无法播放.比如:
CCTV4-国际,http://124.238.110.109:9999udp://@224.254.200.190:6307
CCTV1,http://121.19.134.21:808/iptv/live/1000.json?key=txiptv/tsfile/live/0001_1.m3u8?key=txiptv&playlive=1&authid=0

**Comment by ssili126** [comment]
已经过滤掉udp及rtp的内容。同时增加了测速的脚本，download_speed.py，由于github访问国内数据网速太慢，需要自己单独执行。
