### ISSUE TITLE
请问能否增加电视台图标呢，谢谢

### ISSUE THREAD

**Issue by dahuzi-gege** [ssili126/tv#25]
添加到emby没有电视台标，转换后又不能事实获取您的更新。

**Comment by ssili126** [comment]
是不是频道名称的问题，所以不能获取

**Comment by dahuzi-gege** [comment]
我是直接下载您的m3u文件，然后上传emby没有显示台标，我打开了m3u文件看源代码 里面没有台标的图片地址导致的
