### ISSUE TITLE
能否增加源搜索

### ISSUE THREAD

**Issue by SymonChu** [ssili126/tv#27]
你好，大佬你的项目很好了，但是其实我主要想抓一些凤凰的源，我在酷安网看到一个网友写了一个小软件，他抓源应该是这个网站
www.foodieguide.com

这是他公开的维护源
https://mirror.ghproxy.com/raw.githubusercontent.com/XiaoZhang5656/xiaozhang-5656.github.io/main/iptv-live.txt

这是他写的安卓端的软件
https://www.coolapk.com/feed/52560285?shareKey=ZDdkNmZjMTZkYTI5NjVkZTc3OWM~&shareUid=1620349&shareFrom=com.coolapk.market_14.0.2

好像抓的源很多也不能播放，如果大佬也可以抓多一些源然后自动检测有效性，那是最好了

**Comment by ssili126** [comment]
知足常乐，
没有找到测试稳定的，有会增加的
