### ISSUE TITLE
宝塔不能用webdriver，唉。好可惜

### ISSUE THREAD

**Issue by MemoryCollection** [ssili126/tv#32]
我还寻思部署到服务器上运行那，国内的会好些。大佬有考虑改成requests吗

**Comment by ssili126** [comment]
request运行不了，是不是你没有安装对，linux应该是支持chrome and chromedriver的

**Comment by ssili126** [comment]
你用ubuntu，并安装这个试试，chromium chromium-driver，这样应该是可以的。

**Comment by MemoryCollection** [comment]
![image](https://github.com/ssili126/tv/assets/27777606/06fbd7d6-e287-4417-a585-8ceab591c0b1)
可以了，我只安装chromedriver了，忘记安装chromium了！！！！！

大佬需要国内的源链接不，服务器比较小，就不公开了。需要加我 v：ieve55  我发给你

**Comment by ssili126** [comment]
好的，谢谢了，我加你，

**Comment by uyaboy** [comment]
能不能介绍下如何在宝塔下运行

**Comment by MemoryCollection** [comment]
> 能不能介绍下如何在宝塔下运行

安装好python的依赖后，在终端安装chrome and chromedriver就可以了

**Comment by ssili126** [comment]
apt-get install -y chromium chromium-driver，安装就可以的，早就有人安装成功了

**Comment by uyaboy** [comment]
docker运行成功了，但是脚本一直在跑，服务器CPU总是很高，所以想着在python项目管理器里试试
