### ISSUE TITLE
自动更新太赞了！但是能区分分辨率就好了

### ISSUE THREAD

**Issue by Shanye0109** [ssili126/tv#33]
自动更新太赞了！但是能区分分辨率就好了。很多源都是4:3的比例，看着很难受。不知道大佬会不会更新一下代码，筛选出来16:9的比例的源？

**Comment by ssili126** [comment]
很多频道只有低分辨率，所以没有准备区分。以前有如区分过，删除了。播放器有全屏选项，什么比例的都不影响，都是全屏观看。
