### ISSUE TITLE
win11 x64运行出错

### ISSUE THREAD

**Issue by cn0068** [ssili126/tv#4]
chrome 121.0.6167.85 绿色版本，解压运行。非安装版本。
运行itv.exe出错。
![屏幕截图 2024-01-31 175059](https://github.com/ssili126/tv/assets/62278175/d3c7f827-b057-44dc-b6b7-902bd16de496)

**Comment by ssili126** [comment]
绿色版本找不到目录，要安装版chrome

**Comment by ssili126** [comment]
也可以下载itv.txt直接运行itvtest.exe
