### ISSUE TITLE
docker版本每次都要手动吗

### ISSUE THREAD

**Issue by xiaodan01** [ssili126/tv#42]
安装了docker版本的，运行完容器自己就停止了，还有容器能加个定时运行和端口映射吗，装在乌班图上了，没法直接远程访问

**Comment by ssili126** [comment]
添加乌班图的自动按时运行即可

**Comment by xiaodan01** [comment]
> 添加乌班图的自动按时运行即可

端口呢，能映射一下吗，这样直接就可以远程订阅ip:端口/tv.list了

**Comment by ssili126** [comment]
linux系统可以安装http服务，docker运行时映射到相应文件夹就可以了，
