### ISSUE TITLE
群晖docker运行完不保存文件

### ISSUE THREAD

**Issue by 7noemo** [ssili126/tv#58]
如下图报错：
![image](https://github.com/ssili126/tv/assets/103473489/70070e0b-4910-4d87-be82-c7c36ae33580)

**Comment by ssili126** [comment]
一般是权限的问题，

**Comment by 7noemo** [comment]
> 一般是权限的问题，

前几次还是可以生成新文件的呢

**Comment by ssili126** [comment]
那应该是网站限制访问了，fofa网站有访问次数限制，可以重启路由获取新的IP。

**Comment by 7noemo** [comment]
不确定是什么具体原因，路由重启过，py文件重新修改过，添加了容器端口，正常了。
