### ISSUE TITLE
请教抓取规则

### ISSUE THREAD

**Issue by song2005kai** [ssili126/tv#6]
请教一下，挨个去试接口“/iptv/live/1000.json”这条规则是如何获取（知晓）的？

**Comment by ssili126** [comment]
https://www.jzpu.com/?id=3545，网上有些介绍。还有别的平台。

**Comment by song2005kai** [comment]
这个网站我也看到过，感觉应该不是原文了，少了些东西。里面只讲了通过“zh_cn.js”来定位，剩下的就是频道url 的格式了，所以很纳闷“1000.json”这个规则是怎么产生的。

**Comment by ssili126** [comment]
以前好像就是用的这个，现在没有电脑了，没法再找找了。

**Comment by song2005kai** [comment]
好吧，没关系就是挺好奇的。不过整个脚本已经很不错了，感谢。

**Comment by ssili126** [comment]
谢谢☺️
